### ISSUE TITLE
Can't get .gif to display in GUI

### ISSUE THREAD

**Issue by katrina-barth** [mhuss93/bme547final#8]
Error on line 93 of latest commit on branch KB/SetupGUI_v2_#1 #

**Comment by dward2** [comment]
After some research, I think I understand what is happening with respect to the images only showing when the `window2.mainloop()` command is run.  And, why the second window shows up even without the `window2.mainloop()` command.

Let's answer the second one first.

Your code starts by running the `start_window()` function.  It defines everything about your first window that is stored in the `root` variable.  That procedure ends with `root.mainloop()`.  This essentially starts the Tk interface.  The Tk interface displays the window and monitors for user interaction with the windows.

When you click on "Process my image(s)" button, the Tk interface knows to run the function `image_process()` .  This function then calls the `processed_window()` function.  This creates a second window, `window2` and sets it up.  Then, when this function ends, control is returned to the `root.mainloop()` which is still running in the background, and this displays the new window.  It is not necessary to run a mainloop on window2 because the Tk interface is already running for the root window.

So, why does the image show when you have the `window2.mainloop()` but not when you don't?  It is related to the above.  Let's look at the case when `window2.mainloop()` is not called.  When the `processed_window()` function is called, it creates the variable `processed_image` to hold the image, and this variable is attached to the `processed_image_space` label.  
When `processed_window()` ends, control is returned to the `root.mainloop()`.  Python then does a garbage collection and removes unneeded or out-of-scope variables.  With the end of `processed_window()`, Python thinks that the `processed_image` variable is no longer needed, and so destroys that variable.  But, Tk still needs it.  But, if it isn't there, it displays the blank image.  

But, if you have a call to `windows2.mainloop()`, since this call is made from within the `processed_window()` function, that function doesn't officially end as long as the `windows2` window remains open, and hence the `processed_image` variable isn't destroyed, allowing the image to exist to be displayed.

There is an alternate approach.  You can attach the variable image to the label variable, and it will then remain active within the scope of the window.  In your code, you would add the following line:
```
processed_image_space.label = processed_image
```
When I did that, the image was displayed even without the `windows2.mainloop()`.  

If you develop problems with having too many "mainloop()" commands running, this might provide an alternative.  The following website has some more info:
<http://effbot.org/pyfaq/why-do-my-tkinter-images-not-appear.htm>

Also, something to be aware of, there are two ways of having opening a second window.  The first is following your approach where you also define the second window using the `Tk()` widget.  Another is to use `Toplevel()`.  See the two links below for more info, especially if you start to run into problems.

<https://riptutorial.com/tkinter/example/22130/difference-between-tk-and-toplevel>
<https://tkdocs.com/tutorial/windows.html>

**Comment by katrina-barth** [comment]
Dr. Ward,

Thank you for the follow up on this! This makes sense to me, and also explains why the pre-set selection for the radio button required the mainloop() as well.

My plan as of now for the GUI is to have new windows open from existing windows in order to show certain features, such as the histogram for instance. I’ll read more on these links and figure out if Tk() or Toplevel() make more sense for this sort of organization.

Thanks again,
-Katrina



Katrina Barth

Viventi Lab  -  PhD Student

Department of Biomedical Engineering

Duke University

________________________________
